### ISSUE TITLE
Profiles have inverted_y as <"True">, should be <true>

### ISSUE THREAD

**Issue by hapiel** [plottertools/vpype-gcode#22]
It was misleading that in the bundled profiles and in the readme the `invert_y` option is set to `"True"`. 

I tried to set it to `"False"`, but this did not work because `"False"` is truthy. It turns out it had to be set to `false` (or omitted of course, as the default is false)

I recommend changing all the profiles using this flag from `"True"` to `true`:
`invert_y = true`

**Comment by abey79** [comment]
Good point, I've fixed it.
